### ISSUE TITLE
Create Mongoose adapter

### ISSUE THREAD

**Issue by choutkamartin** [choutkamartin/datapick#5]
https://github.com/nextauthjs/adapters/pull/355

**Comment by paulrajib** [comment]
With '@choutkamartin/mongoose-adapter' how can we call  MongooseAdapter.getUserByEmail(example@gmail.com) to fetch an user or check an user !?

Sorry to ask this way, hope you will understand.

**Comment by choutkamartin** [comment]
@paulrajib You can't call `MongooseAdapter.getUserByEmail`. That's not how Mongoose works. How it works?

You have models. The main structure of a model is defined by its schema.

```js
const userSchema = new mongoose.Schema({
  email: {
    type: String,
    unique: true,
    required: true,
  },
  name: {
    type: String,
  },
});
```

When you export the schema above like this, you get a model.
```js
export default mongoose.models.User || mongoose.model("User", userSchema);
```

When you create a model the way above, you assign that model to an already existing database connection you established.
```js
cached.promise = mongoose.connect(MONGODB_URI, opts).then((mongoose) => {
      return mongoose;
});
```

When you do this, you can then query the database via the models.
```js
const user = await User.findOneAndUpdate(id);
```

The Mongoose adapter you are probably talking about was specifically written only for usage with Next Auth. Only Next Auth should use the adapter as seen below.
```js
import { MongooseAdapter } from "@choutkamartin/mongoose-adapter";
import User from "models/User";

export default NextAuth({
  adapter: MongooseAdapter(process.env.MONGODB_URI)
});
```

If you want to query your own models, you should create your own connection to your database, create your own models and then query via the models your database. **As I've said, you can't use my `@choutkamartin/mongoose-adapter` package to query what you want. It's designed to work only with Next Auth internals.**

Also, read Mongoose and MongoDB documentation, to grasp the fundamentals. 
https://mongoosejs.com/

A year ago I created an example repository for usage of Next Auth and custom (mine) Mongoose adapter or a MongoDB adapter.
https://github.com/choutkamartin/next-auth-mongoose

**And - Mongoose is only an object modelling tool for MongoDB. Take that in mind.**

**Comment by paulrajib** [comment]
Thank you for your kind reply.  I am in your debt.
